export const EDIT_FIELD='EDIT_FIELD';
export const UNEDIT_FIELD='UNEDIT_FIELD';
export const UPDATE_FIELD='UPDATE_FIELD';
export const UPDATE_LOGIN_INFO = 'UPDATE_LOGIN_INFO';
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const ADD_NEW_PROFILE_SUBSECTION = 'ADD_NEW_PROFILE_SUBSECTION';
export const UPDATE_CATEGORY_PROP = 'UPDATE_CATEGORY_PROP';