FROM mongo

MAINTAINER <logeekal> jtn.kathuria@gmail.com

COPY ./mongoEntry.js /

#Now creating user  for development environment
#CMD [ " mongod --fork --logpath /var/log/mongodb.log &&  sleep 5 && mongo ./mongoEntry.js" ]
