version: '3'
services:

  mongo:
    image: mongo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - 27017:27017
    volumes:
      - "./mongoEntry.js:/docker-entrypoint-initdb.d/mongoEntry.js:ro"
      - "mongoData:/data/db"


  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ports:
      - 8081:8081
    links: 
      - mongo:mongo
    depends_on: 
      - mongo

  session-redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - "redisSessionData:/data"
    entrypoint: redis-server --appendonly yes --requirepass R3D1SP@ssword

volumes:
  mongoData:
  redisSessionData: